/**
 * lib/covers.ts
 *
 * Registry of preset cover images shipped in /public/covers/. Each cover
 * has an id, a display name, and a SHA-256 hash that the runtime
 * verifies before embedding. If the file on disk has been swapped or
 * corrupted, embedding refuses to proceed.
 *
 * To regenerate hashes: pnpm covers:generate && pnpm covers:hash
 * Then paste the output of covers:hash into COVER_HASHES below.
 */

import { sha256 } from "./crypto";

export interface Cover {
  id: string;
  name: string;
  url: string;
  /** rough preview hue, used for skeleton placeholders */
  hint: string;
}

export const COVERS: Readonly<Cover[]> = [
  { id: "01-amber-dusk",   name: "Amber Dusk",   url: "/covers/01-amber-dusk.png",   hint: "oklch(35% 0.10 60)"  },
  { id: "02-sea-cliffs",   name: "Sea Cliffs",   url: "/covers/02-sea-cliffs.png",   hint: "oklch(40% 0.08 240)" },
  { id: "03-pine-woods",   name: "Pine Woods",   url: "/covers/03-pine-woods.png",   hint: "oklch(35% 0.06 150)" },
  { id: "04-desert-sand",  name: "Desert Sand",  url: "/covers/04-desert-sand.png",  hint: "oklch(60% 0.10 70)"  },
  { id: "05-night-snow",   name: "Night Snow",   url: "/covers/05-night-snow.png",   hint: "oklch(55% 0.04 250)" },
  { id: "06-rose-fields",  name: "Rose Fields",  url: "/covers/06-rose-fields.png",  hint: "oklch(55% 0.10 10)"  },
  { id: "07-volcano",      name: "Volcano",      url: "/covers/07-volcano.png",      hint: "oklch(35% 0.14 30)"  },
  { id: "08-misty-lake",   name: "Misty Lake",   url: "/covers/08-misty-lake.png",   hint: "oklch(55% 0.02 200)" },
];

// Generated by scripts/hash-covers.ts. Do not edit by hand.
export const COVER_HASHES: Readonly<Record<string, string>> = {
  "01-amber-dusk": "7dab0ee309545d190b6b9f700f1325f176b41cacd772d14d9b8179e502495bf1",
  "02-sea-cliffs": "15415da6c8d49631f6a640b76d86f040d93cbd42e99df64f3b0ed89f29f8fd9b",
  "03-pine-woods": "cc30f14678e9e7d0e8096a83399eb2315c2f6549dd1b19577847ab966d44d3dd",
  "04-desert-sand": "dab81a47c7ff08d0792e9113dae0590f68edfb588fda519d8c6a1fe4ba2ad588",
  "05-night-snow": "a0d6ef4732920465cd40a154b3a3831bdbadb63bf01aad540be076891dfe782d",
  "06-rose-fields": "263ba677fa94637c5d42d70100a48a54fb97cfd3581f28f2c5b25461177f16a8",
  "07-volcano": "1da8d21ec2cf622bd71439ce75fa39933beb04369a6268fb780e991f995aff03",
  "08-misty-lake": "2140ede5505c47ca814f7e148a1e8526b3d23e6aaa3a2ddf88fc3cf758d5b249",
};

export function getCover(id: string): Cover | undefined {
  return COVERS.find((c) => c.id === id);
}

/** Picks a random cover id from a pool, or from all covers if none provided. */
export function pickRandomCoverId(pool?: ReadonlyArray<string>): string {
  const ids = pool && pool.length > 0 ? pool : COVERS.map((c) => c.id);
  const idx = Math.floor(Math.random() * ids.length);
  return ids[idx]!;
}

/**
 * Fetches a cover and verifies its SHA-256 hash matches our build-time
 * record. Returns the verified bytes. Throws if the hash doesn't match.
 *
 * This is a tamper-detection layer, not a security boundary — a hostile
 * actor in a position to swap files in /public/ could also swap the
 * code that does the check. The point is to fail loudly when an
 * accidental file replacement happens (e.g., during deployment).
 */
export async function fetchAndVerifyCover(id: string): Promise<Blob> {
  const cover = getCover(id);
  if (!cover) throw new Error(`unknown cover: ${id}`);
  const expectedHash = COVER_HASHES[id];
  if (!expectedHash) throw new Error(`no hash for cover: ${id}`);

  const res = await fetch(cover.url, { cache: "force-cache" });
  if (!res.ok) throw new Error(`fetch ${cover.url} failed: ${res.status}`);
  const buf = new Uint8Array(await res.arrayBuffer());
  const actual = await sha256(buf);
  if (actual !== expectedHash) {
    throw new Error(
      `cover hash mismatch for ${id}: expected ${expectedHash.slice(0, 12)}…, got ${actual.slice(0, 12)}…`,
    );
  }
  return new Blob([buf as BlobPart], { type: "image/png" });
}
