/**
 * Reads every cover PNG and prints a TS literal you can paste into
 * lib/covers.ts. Re-run after regenerating covers to update hashes.
 *
 * The hash is computed at build time and verified at runtime before
 * embedding — if the file on disk has been tampered with or replaced,
 * the embed pipeline refuses to run.
 */
import { readdirSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";

const COVERS_DIR = resolve(process.cwd(), "public", "covers");

function main() {
  const files = readdirSync(COVERS_DIR)
    .filter((f) => f.endsWith(".png"))
    .sort();

  if (files.length === 0) {
    console.error("No covers found. Run pnpm covers:generate first.");
    process.exit(1);
  }

  const lines: string[] = [];
  lines.push("// Generated by scripts/hash-covers.ts. Do not edit by hand.");
  lines.push("export const COVER_HASHES: Readonly<Record<string, string>> = {");
  for (const f of files) {
    const buf = readFileSync(resolve(COVERS_DIR, f));
    const hash = createHash("sha256").update(buf).digest("hex");
    const id = f.replace(/\.png$/, "");
    lines.push(`  "${id}": "${hash}",`);
  }
  lines.push("};");

  console.log(lines.join("\n"));
}

main();
